
version: '3'

networks:
  integration-test:
    driver: bridge

services:
    taxapi_tests:
        build:
          context: .
          dockerfile: ./Dockerfile.test
        volumes:
            - .:/go/src/target
        depends_on:
            - taxapi
        networks:
            - integration-test
        env_file:
            - ./test.env
    taxapi:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        depends_on:
            database:
                condition: service_healthy
        env_file:
            - ./test.env
        networks:
            - integration-test
    database:
        image: postgres:16.0
        environment:
            POSTGRES_DB: ktaxes
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "127.0.0.1:5432:5432"
        networks:
            - integration-test
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
